dist: xenial

sudo: required

language: python

cache: pip

branches:
    only:
        - master
        - dev

install:
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash

    - command -v nvm
    - nvm install 12 && nvm use 12 && node --version

    - npm install

    # install semver for versioning
    - sudo curl https://raw.githubusercontent.com/fsaintjacques/semver-tool/2.1.0/src/semver -o /usr/local/bin/semver && sudo chmod +x /usr/local/bin/semver
    - semver --version

    # Hub
    - sudo snap install hub --classic
    - hub --version

before_script:
    - git config --global user.name "samirsilwal"
    - git config --global user.email "samirsilwal2424@gmail.com"
script:
    - npm run test
    - ./release.sh
